# This is a basic workflow to help you get started with Actions

name: Update website

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    # Runs a single command using the runners shell
    - name: Build
      run: |
        docker run -v "$PWD":/src ghcr.io/shaddydc/emscripten-magnum-docker:master sh -c "
          cd /src && mkdir build-emscripten && cd build-emscripten &&
          cmake .. -DCMAKE_TOOLCHAIN_FILE="../toolchains/generic/Emscripten-wasm.cmake" -DCMAKE_BUILD_TYPE=RelWithDebInfo &&
          cmake --build . "
          
    - name: Push update
      run: |
        git config --global user.name 'ShaddyDC'
        git config --global user.email 'shaddythefirst@gmail.com'
        git clone https://x-access-token:${{ secrets.WEBSITETOKEN }}@github.com/ShaddyDC/replayer-website
        cp build-emscripten/RelWithDebInfo/bin/* replayer-website/
        cd replayer-website
        git add .
        git commit -m "Update files"
        git push
