name: Update website

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      run: |
        docker run -v "$PWD":/src ghcr.io/shaddydc/emscripten-magnum-docker:master sh -c "
          cd /src && mkdir build-emscripten && cd build-emscripten &&
          cmake .. -DCMAKE_TOOLCHAIN_FILE="../toolchains/generic/Emscripten-wasm.cmake" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=./deploy &&
          cmake --build . --target install"
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './build-emscripten/deploy/'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
          
